### ISSUE TITLE
repositoryContext needs better specification

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-project#142]
ocm generated repo ctx like this:
```yaml
  repositoryContexts:
  - baseUrl: eu.gcr.io
    componentNameMapping: urlPath
    subPath: <some-prefix/abc/def>/microblog
    type: OCIRegistry
```

Clarify:
- Why is baseUrl only a host name and not a full path? Other tools create a full URL here?
- subPath is neither mentioned in the specification nor in the schema.
- Why do we need two fields for this?
