### ISSUE TITLE
Configuration generates invalid yaml for multiline and object content

### ISSUE THREAD

**Issue by dee0** [open-component-model/ocm-project#179]
**What happened**:

My release failed with 
`ocm-system   dmi-broker                           10h   False   Could not load chart: cannot load values.yaml: error converting YAML to JSON: yaml: line 23: could not find expected ':'`

Each of my dictionary and multiline string values were improperly indented.  In the screenshot below you can see on the right hand side my file after Configuration was applied.  Note that certs.rs.crt is improperly indented.  On the left is a copy that I fixed 'by hand' and which is parsable. 

![image](https://github.com/open-component-model/ocm-project/assets/8633549/68e505da-0467-4741-be39-5ccceef3e7eb)

The values.yaml in the dir resource in my component version contains 

```
certs:
 intermediate: unset
 root: unset
 ingress:
  crt: unset
  key: unset
 rs:
  intermediate: unset
  root: unset
  crt: unset
  key: unset

```

My config.yaml in my component version, that is my config for the ocm controller, contains 
defaults
```
configuration:
  defaults:
    certs:
      rs:
        crt: null

```
rules
```
  - value: (( certs.rs.crt ))
    file: dmi-broker/values.yaml
    path: certs.rs.crt

```

Running the command 
`kubectl get -n broker configmap dmi-broker -o=yaml | yq  '.data.config'  | yq  -C | less -iR`
to look at the content of my configmap that is used in my cluster I see the following 

![image](https://github.com/open-component-model/ocm-project/assets/8633549/8f300fef-e22c-4fa5-8cdc-519d5188df86)

Image below shows the 'pipeline' I have defined for the ocm-controller
![image](https://github.com/open-component-model/ocm-project/assets/8633549/7b96adc1-620c-4ce3-a5b1-d5e1e96d3475)

I believe this is an ocm-controller bug because 
- values.yaml in the Localization Snapshot is valid, and
- data in the ConfigMap is valid, but
- values.yaml in the Configuration Snapshot is not valid yaml 

**What you expected to happen**:

I expected the release to work of course :) 

**How to reproduce it (as minimally and precisely as possible)**:

I believe you just need to have a rule that is setting a multiline string value or an object value.

**Anything else we need to know**:

Not that I can think of 

**Environment**:

My ocm-controller was built from this hash of this fork 
https://github.com/dee0sap/ocm-controller/tree/228d0be45540590ea51b712d3fb21d2c2082ef72
because I need my quick fix for https://github.com/open-component-model/ocm-project/issues/68

**Comment by dee0sap** [comment]
I was able to add to the ocm project a test case which I believe reproduced the problem.  You can see what I added in this PR https://github.com/open-component-model/ocm/pull/734

**Comment by dee0sap** [comment]
Think this may be a goccy/go-yaml bug.   Either that or ocm is using replace incorrectly.

https://go.dev/play/p/rfnbY5rbSk9

**Comment by morri-son** [comment]
adding @Skarlso

**Comment by Skarlso** [comment]
Yeah, we are just using whateverm OCM does :)

**Comment by Skarlso** [comment]
Uwe found the issue in the corresponding YAML library. https://github.com/goccy/go-yaml/issues/447

**Comment by morri-son** [comment]
@dee0 confirmed that with using a certain format as input, the lib produces the wanted output. We'll close this issue now and open a new one, checking for a lib that can handle things better.

**Comment by dee0** [comment]
Hey @morri-son 
Actually I haven't confirmed anything yet.

I just tried a new ocm-controller build with @Skarlso's 'don't marshal primitives' change and I think the ocm-controller is still unusable for me.     This because object data is not stored correctly by the configuration.  

Object data is still yielding invalid yaml.  e.g.  I get 

```
  orca_env_stable_values:
 certificate_authority_url: http://example1.com 
 deployment: deveaws
 deployment_size: xsmall
 domain: example2.com 
 landscape_region: eu12
 org: deveaws
 service_hostname_suffix: .example3.com 
 service_kubernetes_hostname_suffix: .example4.com 

```
but it needs to be 

```
  orca_env_stable_values:
    certificate_authority_url: http://example1.com 
    deployment: deveaws
    deployment_size: xsmall
    domain: example2.com 
    landscape_region: eu12
    org: deveaws
    service_hostname_suffix: .example3.com 
    service_kubernetes_hostname_suffix: .example4.com 

```

I have not tried the 'formatting the text the right way' trick for the multiline string data yet.    And I don't know how I can reasonably do that.    In the 'last mile config' we won't know how much indenting is required and in spiff++ I am not seeing a good way to determine and then apply the required amount of indenting.

What I maybe able to do is to use spiff++'s 'asjson' function to double quote the multiline string.    I'll try to give that a shot this weekend.
