### ISSUE TITLE
Default values are not applied to changes if there is no rules but the value is still different

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-project#208]
**What would you like to be added**:

Given a configdata like this:

```yaml
apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
configuration:
  defaults:
    replicas: 2
  rules:
  - value: (( replicas ))
    file: podinfo/values.yaml
    path: replicaCount
  schema:
    type: object
    additionalProperties: false
    properties:
      replicas:
        type: integer
```

We don't check if the default value differs from actual values.

**Why is this needed**:
