### ISSUE TITLE
(resources) `version` seems to be mandatory, although the spec says it's optional

### ISSUE THREAD

**Issue by hilmarf** [open-component-model/ocm-project#223]
**Description**

Try executing the following: `ocm add componentversions --create --file hello-tiny smallest.yaml`

```yaml
# 1 - smallest.yaml
components:
  - name: docker.io/recmo/docker-hello-tiny
    version: v1.0
    provider:
      name: https://hub.docker.com/u/recmo
    resources:
      - name: docker-hello-tiny
        # No version specified!
        type: ociImage
        access:
          type: ociArtifact
          imageReference: docker.io/recmo/docker-hello-tiny:latest
```

This fails with: `Error: failed adding component "[docker.io/recmo/docker-hello-tiny](http://docker.io/recmo/docker-hello-tiny)"(smallest.yaml[1][1]): resources: entry 1: version: Required value: must specify a version`

```yaml
# 2 - smallest.yaml
components:
  - name: docker.io/recmo/docker-hello-tiny
    version: v1.0
    provider:
      name: https://hub.docker.com/u/recmo
    resources:
      - name: docker-hello-tiny
        version: latest # No valid semver!
        type: ociImage
        access:
          type: ociArtifact
          imageReference: docker.io/recmo/docker-hello-tiny:latest
```

This fails with: `Error: failed adding component "[docker.io/recmo/docker-hello-tiny](http://docker.io/recmo/docker-hello-tiny)"(smallest.yaml[1][1]): component.resources.0: Must validate at least one schema (anyOf);component.resources.0.access.type: component.resources.0.access.type must be one of the following: "ociRegistry";component.resources.0.version: Does not match pattern '^[v]?(0|[1-9]\d*)(?:\.(0|[1-9]\d*))?(?:\.(0|[1-9]\d*))?(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'`

Only the following example works currently:

```yaml
# 3 - smallest.yaml
components:
  - name: docker.io/recmo/docker-hello-tiny
    version: v1.0
    provider:
      name: https://hub.docker.com/u/recmo
    resources:
      - name: docker-hello-tiny
        version: v1.0 # Why is this necessary?
        type: ociImage
        access:
          type: ociArtifact
          imageReference: docker.io/recmo/docker-hello-tiny:latest
```

So either we have to change the [spec](https://github.com/open-component-model/ocm-spec/blob/e39321a6caef69f79db7f11a38951f7758f8d152/doc/01-model/03-elements-sub.md?plain=1#L43) or our coding.

**Done Criteria**
- [ ] `ocm add componentversions ...` doesn't fail, when there is a resource specified without `version`
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review
