### ISSUE TITLE
Improve and Extend the schema used for validation and auto-completion

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#234]
**Description**

In #198 we introduced a schema to validate component constructors and deliver auto-completion: https://github.com/open-component-model/ocm-website/blob/main/static/schemas/configuration-schema.yaml.

In the next step all nodes should get:

- descriptions including links to the OCM documentation, preferably the documentation contains examples
- defaults
- examples

similar to 

```
            imageReference:
              type: 'string'
              description: |
                OCI image/artifact reference.
                [See the documentation](https://ocm.software/docs/guides/input_and_access/#ociartifact)
              default: 'ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.7.0'
              examples: ['nginx:1.25.4', 'eu.gcr.io/gardener-project/landscaper/examples/charts/guided-tour/echo-server:1.0.0', 'ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.7.0', 'ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image@sha256:7b3399da19561d3c54bab9d694126174c334a4a080176cb99186ea4075aff3db', 'ghcr.io/open-component-model/ocm/ocm.software/ocmcli/ocmcli-image:0.7.0@sha256:4f5d0d0684a1ed9f7ce482c87c2c4d3499468fdcea2711f0c3f6a69a7aa9147b']
```
