### ISSUE TITLE
Figure out how to auto label things for IPCEI

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-project#248]
As a first, let's label everything and then, go from there to unlabel things that don't need that label.

**Comment by Skarlso** [comment]
<img width="938" alt="Screenshot 2024-09-13 at 12 48 23" src="https://github.com/user-attachments/assets/2bf65559-7e18-4baf-add8-1b4abbc6bd5f">

It's working on the ocm-project repo... Just need to add THIS workflow for all repos that we would like to watch:

```yaml
name: Label issues
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: area/ipcei
```
