### ISSUE TITLE
Enhance the OCM GitHub Action with the ability to configure OIDC and release it to the marketplace

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#253]
**What would you like to be added**:
The current [GitHub Action for ocm](https://github.com/open-component-model/ocm-action/tree/main) only allows password based authentication for the registry to be pushed to. This should be enhanced to accept authentication using OIDC. This is possible [as described in](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) and available for all Hyperscalers and even other platforms, e.g. PYPI. 

A well documented description and example how to configure this for the Google Artifact Repository can be found on [medium.com](http://medium.com/).

**Why is this needed**:
Using basic authentication should be avoided wherever possible. The main reason is that passwords need to be rotated. Using OIDC it is possible to avoid secret rotation and remove this manual part of the configuration.

**Comment by morri-son** [comment]
@hilmarf , maybe a good topic as follow-up to the area you're currently work in

**Comment by ccwienk** [comment]
btw, might re-use existing actions, like so:
```
- name: Google-Auth
  id: auth
  uses: google-github-actions/auth@v2
  with:
    token_format: access_token
    project_id: ${{ env.PROJECT_ID }}
    service_account: ${{ env.SERVICE_ACCOUNT }}
    workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
- name: docker-auth
  id: docker-auth
  uses: docker/login-action@v1
  with:
    username: oauth2accesstoken
    password: ${{ steps.auth.outputs.access_token }}
    registry: ${{ env.AR_REPO_LOCATION}}.pkg.dev                     
```
(I already validated this successfully)
