### ISSUE TITLE
Additional resources in toiPackage, other than config and credentials, aren't usable

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-project#350]
**What happened**:

I added these to my toiPackage 
```
additionalResources:
  configFile:
    resource:
      name: toi-package-additional-resource-config
  credentialsFile:
    resource:
      name: toi-package-additional-resource-credentials
  readme.txt: # OCM TOI doesn't seem to do anything with this
    resource:
      name: toi-package-additional-resource-readme
```

While the command 
```
ocm toi configuration bootstrap 'directory::../ocm/component-archive//example.com/ocm/toi/helloworld:1.0.0'
```
extracts the config and credentials file it seems nothing in OCM will make use of the other additionalResources

**What you expected to happen**:

At minimum, the doc should indicate how other additional resources may be used.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know**:

Nope 

**Environment**:

ocm version 0.11.0
