### ISSUE TITLE
Doc and errors don't say that OCM TOI config and credential additional resources must be type yaml

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-project#351]
**What happened**:

I added the following to my toiPackage 

```
additionalResources:
  configFile:
    resource:
      name: toi-package-additional-resource-config
  credentialsFile:
    resource:
      name: toi-package-additional-resource-credentials
```

My component descriptor had 

```
- name: toi-package-additional-resource-config
  version: *version
  type: file
  input: 
    type: file 
    path: ../toiPackage/additionalResourceConfig.yaml
- name: toi-package-additional-resource-credentials
  version: *version
  type: file
  input: 
    type: file 
    path: ../toiPackage/additionalResourceCredentials.yaml
```

The command 
```
ocm toi configuration bootstrap 'directory::../ocm/component-archive//example.com/ocm/toi/helloworld:1.0.0'
```
unexpectedly reported 
```
Error: {configuration template resource: component resource ""name"="toi-package-additional-resource-config"" not found, credentials template resource: component resource ""name"="toi-package-additional-resource-credentials"" not found}
```

Looking into code I see that the resource type must be `yaml`.'    

**What you expected to happen**:

If the resources must be of type yaml then 
- The documentation should say so 
- If resources that match the name but not the type are found then the warning should indicate that likely the component descriptor has the wrong resource type specified

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know**:

Nope

**Environment**:
ocm version 0.11.0
