### ISSUE TITLE
Consumers in credential file of 'ocm toi bootstrap package' command can only be resolved via global, i.e. .ocmconfig.

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-project#365]
**What would you like to be added**:

In order to make `ocm toi bootstrap package` more usable it would be best if :
a.) The user only had to provide 1 file related to credentials, or if that is not possible then
b.) Prototypes of all required files would be available via `ocm toi configuration bootstrap `

Issue [350](https://github.com/open-component-model/ocm-project/issues/350) prevents (b)

Regarding (a), currently if required credentials are in a repository such as Vault then the user has to provide both a credentials file and an ocmconfig file.   This because the credential handling works as follows 
- The installer author specifies what credentials are required using CredentialRequests in their install definition 
- The function [GetCredentials](https://github.com/open-component-model/ocm/blob/4a1aa4fa4668b2a0758a0d0a2d2c0e7c5d180d7e/api/ocm/tools/toi/install/credentials.go#L64) requires that each CredentialRequest is matched to an entry in the credentials file
- Each of the above matches is evaluated.   Whatever credentials result from the evaluation are what is used to satisfy the request.
- Entries that are in the credential file but that aren't matched to requests from the installer are ignored
- The evaluation only looks at credentials that come from ocmconfig or are hard coded in the credentials file

So for example the installer needs OCIRegistry credentials and the user has them in vault, they _cannot_ do anything like this in their credentials file :
```
credentials:
  myPackageOCI: 
    consumerId:
      type: OCIRegistry
  myVault: 
    consumerId:
        type: HashiCorpVault 
        serverURL: https://myvault.example.com
        mountPath: "my-engine/my-engine-root"
        path: "path/to/my/secret"
        credentialsName: "myPackageOCI"
```

Instead they need 
- A credentials file with just the myPackageOCI as above, and
- an ocmconfig file like :

      ```
      type: generic.config.ocm.software
      configurations:
      - type: memory.credentials.config.ocm.software
        repoName: default
        credentials:
        - credentials:
            authmeth: approle 
            roleid: myroleid
            secretid: mysecretid
          credentialsName: myVault
      - type: credentials.config.ocm.software
        consumers:
        - identity:
            type: OCIRegistry
          credentials:
            - type: HashiCorpVault 
              serverURL: https://myvault.example.com
              mountPath:  "my-engine/my-engine-root"
              path: "path/to/my/secret"
              credentialsName: "myPackageOCI"
        - identity:
            type: HashiCorpVault
          credentials:
          - credentialsName: myVault
            repoName: default
            type: Memory
      ```

If the process was something like below then it would be possible for just a credentials file to be used :
```
 cfg := config.New()
 mem := memorycfg.New("default")
 memrepo := memory.NewRepositorySpec("default")
 inMemoryCredentialContext = newCredentialContext() // Need to implement this func

 evaluatedCredentials  := map[string]CredentialSpec{}
 unevaluatedCredentials  = copy( spec.Credentials )
notInCtx := map[string]bool{}

for len( unevaluatedCredentials  ) > 0 {
  evaluatedCredentialsCount := len( evaluatedCredentials  )
  list := errors.ErrListf("providing requested credentials")

  for name, credSpec := range unevaluatedCredentials  {
      var creds common.Properties
      var consume credentials.ConsumerIdentity
      creds, consumer, err = evaluate(inMemoryCredentialContext , &credSpec ) 
      if  err != nil && ! notInCtx[name] {
        creds, consumer, err = evaluate(ctx, &credSpec ) 
        notInCtx[name] = true
      }
      if err == nil {
         delete unevaluatedCredentials[ name ]
         evaluatedCredentials[name] = credSpec
         // Add result to mem 
         // Add to inMemoryCredentialContext for future evaluation
       } else { 
           list.Add(err)
       }
  }

  if evaluatedCredentialsCount == len( evaluatedCredentials  ) {
     return nil, nil, list.Result()// Give up, return last error 
   }
}

// Now loop over credential requests and attempt to fulfill them results above.
// Similar to original code but without the need to evaluate CredentialSpecs 
// as it has been done already
```

**Why is this needed**:

To make `ocm toi bootstrap package` more usable.
