### ISSUE TITLE
EPIC: Design & Develop an OCM Plugin Registry via Github

### ISSUE THREAD

**Issue by jakobmoellerdev** [open-component-model/ocm-project#374]
The plugins supported by OCM are currently pullable in OCM v1 through component versions and a special resource type that marks them as plugins. That means that effectively to publish a plugin, an OCM component version must exist.

We need to unify this understanding with the new plugin ideations from the Plugin ADR from [Create an ADR for the new OCM Plugin System #379](https://github.com/open-component-model/ocm-project/issues/379)

This system needs to be able to
- Support Fetching/Downloading Plugins for the correct binary architecture and load them into the filesystem based on a well known registry (based on a source provider such as github). Think of a community contributions repository that is similar to homebrew

**Not in scope for this issue anymore:**
- These plugins must be able to be fetched dynamically when not present (ie. when the orchestrator CLI encounters an access type of type `OCIRegistry` and there is no support available, the plugin registry may be queried for any supporting plugins for that type) This querying can then be used to retrieve the correct plugin. 

We decided to descope this due to timeline constraints. We thought this is okay because it is a feasible workaround to merely have a primitive `ocm setup` command, as long as we merely have the `helm` plugin and perhaps the `cosign` plugin. This feature is a prerequisite for rolling out more plugins, so this should still be tackled rather sooner than later!

Follow-Up EPIC: https://github.com/open-component-model/ocm-project/issues/526

**Comment by fabianburth** [comment]
removed since it is not crucial for prototype, still relevant for final delivery

**Comment by Skarlso** [comment]
# Plugin Manifest Files

Each plugin needs a manifest file describing the plugin. Something like this should work:
```yaml
name: "oci-repository"
version: "1.2.3"
capabilities:
  - OCIRepository/v1
  - CommonTransportArchive/v1
architectures:
  - os: linux
    arch: amd64
    url: "https://example.com/plugins/oci-repository-linux-amd64.tar.gz"
    checksum: "sha256:1234abcd..."
  - os: darwin
    arch: arm64
    url: "https://example.com/plugins/oci-repository-darwin-arm64.tar.gz"
    checksum: "sha256:5678efgh..."
maintainer: "Open Component Model"
documentation: "https://example.com/docs/oci-repository"
```

This manifest is then loaded and listed in an index manifest that is later used for discovery.
If OCI registries are involved this could be a specific media-type and then discovery is trivial.

# Registry configuration

Location and potential credentials need to exists for the registry. These could also be done via a configuration file, or leverage ocm's configuration entity. At the very least the following information would be required:

```yaml
registries:
  - name: "official"
    url: "https://github.com/organization/transfer-plugins"
    type: "github"
    priority: 1 # weighting could be added for order of searching the registries
  - name: "personal"
    url: "https://private-registry.example.com"
    type: "http"
    auth: # would be handled by OCM credentials
    priority: 2
```

# Plugin Discovery Process 

When a command like `transfer` is invoked requiring a capability not present locally:

0. Load all registry configurations ( multiple registries could exist )
1. The CLI shall determine the required capability ("OCIRepository")
2. Check if the plugin is registered in code or locally available
4. For each registry, fetch index of available plugins and filter plugins based on the required capability
5. From matching plugins, select the most appropriate version for the current OS and architecture
6. Actually fetch the plugin and check the checksum validity
7. Extract under configured location `~/.config/ocm/plugins/{plugin-name}/{version}/`
8. Proceed with starting the plugin

# Registry Index Structure

Each registry would require some kind of index file manifest to discover plugins.

```yaml
updated: "2025-03-15T12:00:00Z"
plugins:
  - name: "oci-repository"
    versions:
      - version: "1.2.3"
        manifest: "https://github.com/organization/transfer-plugins/manifests/oci-repository-1.2.3.yaml"
      - version: "1.1.0"
        manifest: "https://github.com/organization/transfer-plugins/manifests/oci-repository-1.1.0.yaml"
  - name: "github"
    versions:
      - version: "2.0.1"
        manifest: "https://github.com/organization/transfer-plugins/manifests/github-2.0.1.yaml"
```

# Versioning

The CLI could be used to discover and list plugins potentially for all configured registries. Something like `ocm plugins list` with further configurations for selecting specific registries.

# Life-cycle

The CLI again, could be used to manage life-cycle of plugins, such as, downloading the latest version and checking compatibility of these plugins and verifying structural integrity by checking the checksum value.
