### ISSUE TITLE
Prototoype a new version of the Credential + Config Systems

### ISSUE THREAD

**Issue by jakobmoellerdev** [open-component-model/ocm-project#375]
We need to be able to dynamically pass credentials to plugins.

This is especially difficult because

Credentials need to be resolved before they are passed, otherwise plugins would have to know certain repository systems (such as vault) to be able to access these secrets. The resolution of the secret from an Identity is challenging (understatement looking at the current credential resolution code in OCM v1) and we will face troubles trying to integrate it all. 

We need to find a version of the credential system that works based on identity resolution without inferring the huge complexity of the OCM config onto developers and users when they want to use it.

Acceptance Criteria:
- [ ] Only credentials that are relevant for the plugin should be passed
- [ ] Credentials that need resolution (such as entries for repositories) need
- [ ] Please consider parsing credentials with the CLI (direct passing of credentials outside the config)
- [ ] Credentials should still be able to be derived from .ocmconfig
- [ ] Plugins should not need to call other plugins to resolve credentials

**Comment by hilmarf** [comment]
one currently real life sample:

```bash
ocm --cred :type=JFrogHelm --cred :hostname=******** --cred username=******** --cred password=******** transfer cv --recursive --copy-resources -f ocm-helm-test destination.repository.host --uploader 'plugin/jfrog/JFrogHelm={"url":"helm.destination.repository.host","repository":"ocm-helm-test","type":"JFrogHelm/v1alpha1"}'
```

it's not necessary required to keep that style, but it's very essential to have the possibility to pass configuration (incl. credentials) via commandline

**Comment by dee0sap** [comment]
Hey @jakobmoellerdev and @hilmarf 

Is there a document that describes why a new system is needed?

**Comment by jakobmoellerdev** [comment]
Currently this effort is part of a larger initiative to reimagine the OCM plugin ecosystem: https://github.com/open-component-model/ocm-project/issues/360

The main motivation is that we do not want to have a monolithic core anymore in which plugins get called, but rather have the ability for plugins to completely control the behavior of an OCM repository. This means that plugins have now significantly increased importance.

This ticket is not necessarily gonna kill the old configuration system. Rather its about trying to make the new plugin system interact with the credential system we have and then make necessary changes to adopt to that.

**Comment by dee0sap** [comment]
Thanks @jakobmoellerdev for the link an the explanation. 

Also I see that point #3 indicates that copying the existing 'type registration' system is in consideration.  :)

**Comment by jakobmoellerdev** [comment]
The current credential system turns out to be a rather tough nut. There is very detailed, very complex cyclic analysis coding through stacks (https://github.com/open-component-model/ocm/blob/4a1aa4fa4668b2a0758a0d0a2d2c0e7c5d180d7e/api/credentials/internal/consumers.go) that we do not want to continue with due to its obscurity.

We tried to model it out again for sanity purposes, but this is a gigantic data structure.

![Image](https://github.com/user-attachments/assets/55e63912-69ca-40c0-b001-b81f042957b4)

The main reasons this is an issue is because
1. We currently allow recursive references of credentials (Vault credentials contains Vault credentials contains ....)
2. We want to resolve these recursive references with plugins for plugins in the orchestrator (this is equivalent to OCMv1)

**Comment by dee0** [comment]
Hey @jakobmoellerdev 

While I have looked at the relevant code as a result of insufficient doc/examples I haven't looked at it in depth enough to notice the complexity you are mentioning.

That said 
- Once I got my toi examples [here](https://github.com/dee0/ocm-toi-helloworld/tree/main/examples) working for the scenario were my OCI repo credentials were successfully coming from Vault from a user perspective it did seem to be convenient to use.   I hope that convenience doesn't get lost 
- If by 'recursive', you mean that some credentials for accessing a vault server are located in a vault server, which may or may not be the same vault server, I can imagine us needing that in the project I am currently involved with.    We migrating from one hosted k8s solution to another and as we do so I expect our gitops will need to work with multiple Vaults at the same time.   So it would also be good if the ability to handle this scenario doesn't get lost.

**Comment by jakobmoellerdev** [comment]
> Once I got my toi examples [here](https://github.com/dee0/ocm-toi-helloworld/tree/main/examples) working for the scenario were my OCI repo credentials were successfully coming from Vault from a user perspective it did seem to be convenient to use. I hope that convenience doesn't get lost

Currently we do no plan on continuing to support vaults direct repository integration with OCM, and want to push for a model where Vault credentials are resolved in advance via vault CLI or helpers.

> If by 'recursive', you mean that some credentials for accessing a vault server are located in a vault server, which may or may not be the same vault server, I can imagine us needing that in the project I am currently involved with. We migrating from one hosted k8s solution to another and as we do so I expect our gitops will need to work with multiple Vaults at the same time. So it would also be good if the ability to handle this scenario doesn't get lost.

Similarly, this would need to be handled outside of the core of OCM.

I will bring your concerns back to the round to reevaluate but since TOI is not planned to be continued as is I cannot promise anything in that regard right now

**Comment by jakobmoellerdev** [comment]
I just read your specific use case here

```
type: generic.config.ocm.software
configurations:
- type: memory.credentials.config.ocm.software
  repoName: default
  credentials:
  - credentials:
      authmeth: approle 
      roleid: "my-role-id"
      secretid: "my-secret-id"
    credentialsName: myVault
- type: credentials.config.ocm.software
  consumers:
  - identity:
      type: OCIRegistry
    credentials:
      - type: HashiCorpVault 
        serverURL: "https://myvault.example.com/"
        mountPath: "my-engine/my-engine-root"
        path: "my/path/to/my/secret"
        credentialsName: "my-secret-name"
  - identity:
      type: HashiCorpVault
    credentials:
    - credentialsName: myVault
      repoName: default
      type: Memory
- type: logging.config.ocm.software
  contextType: default
  settings:
    defaultLevel: Warn
```

from what I understand this is a 1:1 mapping to vault that could easily be extracted. Do you have a case in which you need dynamic credential mappings from vault based on identity?

**Comment by jakobmoellerdev** [comment]
Btw another small simplification would be 

```
type: generic.config.ocm.software
configurations:
- type: credentials.config.ocm.software
  consumers:
  - identity:
      type: OCIRegistry
    credentials:
      - type: HashiCorpVault 
        serverURL: "https://myvault.example.com/"
        mountPath: "my-engine/my-engine-root"
        path: "my/path/to/my/secret"
        credentialsName: "my-secret-name"
  - identity:
      type: HashiCorpVault
    credentials:
    - properties:
        authmeth: approle 
        roleid: "my-role-id"
        secretid: "my-secret-id"
      type: Credentials
- type: logging.config.ocm.software
  contextType: default
  settings:
    defaultLevel: Warn
```

Im thinking that before passing configuration we can resolve this to

```
type: generic.config.ocm.software
configurations:
- type: credentials.config.ocm.software
  consumers:
  - identity:
      type: OCIRegistry
    credentials:
      - type: Credentials 
        properties:
          credentials:
            myPackageOCI: 
              consumerId:
                type: OCIRegistry
- type: logging.config.ocm.software
  contextType: default
  settings:
    defaultLevel: Warn
```
with a credential plugin that can get called by us. this could be made recursive but im not sure if we will actually proceed with this
