### ISSUE TITLE
simplify yaml localization

### ISSUE THREAD

**Issue by sk31337** [open-component-model/ocm-project#380]
**Why is this needed**:
As of today, OCM localization is very powerful and can do _nearly_ everything, except bringing me coffee or beer! This functionality is perfect fit for _godlike_ cloud engineers but often you need simple functionality without the need to master the system itself.

Therefore I would like to request a simplification within the scope of localization of yaml files, specifically k8s manifests.

** Context / Situation **:

my `component-constructor.yaml` look like this:

```yaml
components:
- name: GitHub.com/mvp-ocm-test
  labels:
  - name: "org.opencontainers.image.source"
    value: "lieber-gruss-von-johannes-und-steffen"
  provider:
    name: explorer
  version: v0.0.4
  resources:
  - name: provider-kubernetes
    type: ociImage
    version: 0.15.0
    access:
      type: ociArtifact
      imageReference: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.15.0
  - name: provider-helm
    type: ociImage
    version: 0.19.0
    access:
      type: ociArtifact
      imageReference: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
  - name: k8s-manifests
    type : fileSystem
    input:      
      type: dir
      path: ../manifests/helm/umbrella/k8s-manifests/
```

my `manifests/helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml` contains 

```yaml
---
# Source: /helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.15.0
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: pull-secret
---
# Source: /helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: pull-secret
---

```

**What would you like to be added**:

I would like to instruct ocm at design/bundeling/transport time (e.g. before OCM OCI artefact is transported), that it replaces ` xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.15.0` with the new location of the ocm resource `provider-kubernetes`.

From my point of view, it is not necessary that OCM cli is automatically detecting and replacing the OCI urls! I would much rather prefer to leverage tokens (e.g. "{{ .ocm.resources.provider-kubernetes.package.url }}") to explicitly tell ocm what and where to substitute.

e.g. `manifests/helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml` post template of k8s manifest  but pre ocm transport:

```yaml
---
# Source: /helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "{{ .ocm.resources.provider-kubernetes.package.url }}"
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: pull-secret
---
# Source: /helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: "{{ .ocm.resources.provider-helm.package.url }}"
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: pull-secret
---
```

which will be localised post ocm transport to OCI registry some.other.registiry.somewhere:
```yaml
---
# Source: /helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "some.other.registiry.somewhere/crossplane-contrib/provider-kubernetes:v0.15.0"
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: pull-secret
---
# Source: /helm/umbrella/k8s-manifests/charts/name123/templates/pkg-crossplane-provider.yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package:  "some.other.registiry.somewhere/crossplane-contrib/provider-helm:v0.19.0"
  packagePullPolicy: IfNotPresent
  packagePullSecrets:
  - name: pull-secret
---
```

I know that this is already somehow possible as of today with https://github.com/open-component-model/ocm-k8s-toolkit/blob/main/internal/controller/localization/testdata/deployment-instruction-helm/templates/deployment.yaml & https://github.com/open-component-model/ocm-k8s-toolkit/blob/main/internal/controller/localization/testdata/localization-config.yaml.

Neverless I would like to request that the proposed simplified yaml localization functionality is built without the need to define `kind: LocalizationConfig` or more complex substitution implementation.

To decrease complexity at ocm side, this kind of yaml parsing/substitution/lokalization functionality may only be used, when explicit annotation are set at `component-constructor.yaml` 

```yaml
components:
- name: GitHub.com/mvp-ocm-test
  provider:
    name: explorer
  version: v0.0.4
  resources:
  - name: provider-kubernetes
    type: ociImage
    version: 0.15.0
    access:
      type: ociArtifact
      imageReference: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.15.0
  - name: provider-helm
    type: ociImage
    version: 0.19.0
    access:
      type: ociArtifact
      imageReference: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.19.0
  - name: k8s-manifests
    type : fileSystem
    labels:
     - name: "ocm/localization/yaml"
       value: true
    input:      
      type: dir
      path: ../manifests/helm/umbrella/k8s-manifests/
```

--------

I hope this helps you, to understand my proposal better to simplify localization in context of yaml documents.
