### ISSUE TITLE
Component Level Transformers

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm-project#442]
**Description**  
The goal of this task is to implement the component level operations as transformers in the transfer spec. This effectively makes the **transfer spec** a **transformation spec**.

So far, we said that component level operations are determined and done implicitly by our implementation. The arguments therefore were:
- resources are generic and operations on the resource are therefore use case specific
- component descriptors are part of our domain/framework and we can opinionate on it (to avoid complexity)

The integration of the KRO dependency model with CEL expressions changed this view. Through the CEL expression based dependencies, the power of also having this transformation model on component level becomes a **significant value add**.

Implementation-wise, we can build a common uniform dependency graph containing component transformations and resource transformations as nodes/vertexes. 
- the dependencies (edges) between the parent and child components will remain
- additionally, edges might be added for CEL expression dependencies between transformations

We will still perform cycle checking. CEL expression dependencies from child to parent will always result in a cycle.

The spec might look like this (verify while attempting to implement and adjust as needed!)

**Example Spec:**
```
type: graph.transformation.ocm.component/v1alpha1
transformations:
- type: transformation.ocm.component/v1alpha1
  transformations:
    - type: downloader.ocm.component/v1alpha1
      source:
        type: CommonTransportFormat/v1
        name: github.com/ocm-component
        version: v1.0.0
        filePath: ./test/localization-component/archive
    - type: transformation.ocm.resource/v1alpha1
      resources:
      - name: myimage
        transformations:
        - type: downloader.oci/v1alpha1
        - type: uploader.oci/v1alpha1
          imageReference:
            ghcr.io/jakobmoellerdev/images/myimage:after-localize
          id: magic
      - name: mychart
        transformations:
          - type: downloader.oci/v1alpha1
          - type: oci.to.tar.transformer/v1alpha1
          - type: yaml.engine.localization/v1
            file: "*/values.yaml"
            mappings:
              - path: "image.repository"
                value: "${magic.access.imageReference.parseRef().registry}/${magic.access.imageReference.parseRef().repository}"
          - type: tar.to.oci.transformer/v1alpha1
          - type: uploader.oci/v1alpha1
            imageReference:
              ghcr.io/jakobmoellerdev/charts/myimage:after-localize
    - type: signing.ocm.component/v1alpha1
      algorithm: RSA-PSS
      parameters:
    - type: uploader.ocm.component/v1alpha1
      target:
        type: CommonTransportFormat/v1
        filePath: ./test/localization-component/archive-after-localization
```

**Consequence:**
All plugins, including signing, will have to be modelled and implemented (/adjusted)as a transformer.

**Done Criteria**  
- [x] Unit Tests created for new code or existing Unit Tests updated
- [x] Successful demonstration in Review
