### ISSUE TITLE
EPIC: provide built-in substitution engine for OCM CLI v2

### ISSUE THREAD

**Issue by ikhandamirov** [open-component-model/ocm-project#500]
**Description**  

OCM CLI V1 `add` commands have the following parameters (see e.g. [ocm add resources](https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_add_resources.md)):
- `--templater`
- `--settings`

It is helpful, as it allows inputs to be based on templates. A similar possibility is also needed to OCM V2

**Example**

The Piper step `sapOcmCreateComponent`uses it as follows.

1. The user provides a `component-constructor.yaml`

```yaml
components:
- name: ${componentName}
  version: ${artifactVersion}
  provider:
    name: ${provider}
  sources:
  - name: src
    type: filesystem
    access:
      type: gitHub
      repoURL: ${gitURL}
      commit: ${gitCommitId}
  resources:
  - name: ${OCI_NAME_0}
    type: ociImage
    version: ${artifactVersion}
    access:
      type: ociArtifact
      imageReference: ${OCI_REFERENCE_0}
  - name: ${HELM_CHART}
      type: helmChart
      version: ${artifactVersion}
      access:
        type: helm
        helmChart: ${HELM_CHART}
        helmRepository: ${HELM_REPOSITORY}
        version: ${HELM_VERSION}
```

2. The build pipeline generates a `settings.yaml`
```yaml
artifactVersion: 0.0.1-dev-20240918153148+97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
componentName: open-component-model.sap.com/hello-ocm-helm
gitCommitId: 97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
gitURL: https://github.tools.sap/open-component-model/hello-ocm-helm
provider: SAP SE (open-component-model)
OCI_NAME_0: hello-ocm-helm-image
OCI_REFERENCE_0: 371000108081-20240924-072300486-87.staging.repositories.cloud.sap/hello-ocm-helm:0.0.1-dev-20240924072222_7e63e6490e8a5d47ee14ca12500ad7aeea854b90
HELM_CHART: hello-ocm-helm
HELM_VERSION: 0.0.1-dev
HELM_REPOSITORY: https://staging.repositories.cloud.sap/stage/repository/371000698081-20240918-153224840-252
```

3. A component version is created by the following command

```console
ocm --loglevel Debug add componentversion --create --settings settings.yaml --file myTarget/ctf --templater subst component-constructor.yaml
```

4. The result:
```yaml
components:
- name: open-component-model.sap.com/hello-ocm-helm
  version: 0.0.1-dev-20240918153148+97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
  provider:
    name: SAP SE (open-component-model)
  sources:
  - name: src
    type: filesystem
    access:
      type: gitHub
      repoURL: https://github.tools.sap/open-component-model/hello-ocm-helm
      commit: 97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
  resources:
  - name: hello-ocm-helm-image
    type: ociImage
    version: 0.0.1-dev-20240918153148+97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
    access:
      type: ociArtifact
      imageReference: 371000108081-20240924-072300486-87.staging.repositories.cloud.sap/hello-ocm-helm:0.0.1-dev-20240924072222_7e63e6490e8a5d47ee14ca12500ad7aeea854b90
  - name: hello-ocm-helm
      type: helmChart
      version: 0.0.1-dev-20240918153148+97feb5d34cebc31a8f9c56c8cd4fd8ff8003cd1e
      access:
        type: helm
        helmChart: hello-ocm-helm
        helmRepository: https://staging.repositories.cloud.sap/stage/repository/371000698081-20240918-153224840-252
        version: 0.0.1-dev
```
