### ISSUE TITLE
ocm controller helm chart to facilitate adding custom labels to clusterrole

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-project#518]
**Description**  
While we wait for Managed Control Plane to provide the OCM Controller as a component ( e.g. like Flux ) we will be installing it ourselves.

The MCP comes with a couple of admin roles 'out of the box' and these support aggregation.  e.g.
```
aggregationRule:
    clusterRoleSelectors:
        - matchLabels:
            openmcp.cloud/aggregate-to-admin-clusterscoped: "true"
        - matchLabels:
            rbac.crossplane.io/aggregate-to-admin: "true"
        - matchLabels:
            core.orchestrate.cloud.sap/aggregate-to-admin: "true"
```

When we install the OCM Controller's helm chart we want to be able to provide custom labels that will be applied to the ClusterRole(s) it is creating so that those will be aggregated to the MCP admin roles.  

Similar thing for Crossplane.   That is, we intent to create OCM delivery objects, e.g. ComponentVersion, via provider-kubernetes and so if possible would like grant it permission through aggregation.
