### ISSUE TITLE
Make instances dynamically detect changes of its owned resources based on informers

### ISSUE THREAD

**Issue by frewilhelm** [open-component-model/ocm-project#634]
**Description**

As a result of this [spike](https://github.com/open-component-model/ocm-project/issues/456#issuecomment-2796235388), we noticed that the resources orchestrated/deployed by an instance of a `ResourceGraphDefinition` are not reconciled on changes on the resources.

Consider a `ResourceGraphDefinition` that contains one resource:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: simple
spec:
  schema:
    apiVersion: v1alpha1
    kind: Simple
  resources:
    - id: pod
      template:
        apiVersion: v1
        kind: Pod
        metadata:
          name: shell-pod
        spec:
          containers:
            - name: shell-container
              image: alpine:latest
              stdin: true
```

and its instance

```yaml
apiVersion: kro.run/v1alpha1
kind: Simple
metadata:
  name: simple
````

After creating the instance, the resource `pod/shell-pod` is created. However, changing the spec of that resource, does not reconcile the instance and its child-resources immediately. Accordingly, drift is happening.

**Goal**
The goal of this task is to enable KRO to trigger instance reconciliation if one of the instances resources changes (this would also be the foundation for more sophisticated drift-detection / drift-correction). 

We propose a implementation that
- sets up dynamic informers for each resource kind contained in an RGD (which are all the resource kinds that will be deployed and owned by instances of that RGD)
- registers event handlers that triggers the owning instance to be reconciled if a resource changes

In alignment with the KRO maintainers, we propose to introduce this as an opt-in feature (at least initially). We propose the feature flag to be implemented as annotation on the RGD.

**Important Notes**
There currently is an alternative proposal to implement this feature with a custom watch management implementation (called "watchsets"). The primary argument for this custom implementation is performance, as it sets up watches for individual resources (instead of resource kinds with potential additional filters)  and does not do any caching. But we have concerns, since the watchset implementation is not battle tested and currently seems to have several short comings, such as doing an initial list call when starting to watch (and thus also, setting up watches correctly after e.g. having lost network connection). Caching might actually be beneficial, since the resources might actually be required to evaluate the cel expressions. 
Also mainly, the watchset implementation is quite complex and might turn out to be hard to maintain. That's why we proposed an informer based implementation. **Although ultimately, we could live with either solution!**

So, besides the implementation itself, this task involves significant coordination and discussions with the KRO community, both in community as well as on the PR itself.

**Done Criteria**
- [x] Check out existing issues/contribution/discussions about that topic
- [x] Deep-dive into the kro code and understand why there is no such drift detection
- [ ] Code has been reviewed by the KRO community
- [x] Analysis of existing tests (Unit and Integration)
- [x] Unit Tests created for new code or existing Unit Tests updated
- [x] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Internal technical Documentation created/updated (if applicable)
- [ ] Successful demonstration in Review
