### ISSUE TITLE
Helmcharts not easy to consume, missing logic in processing one of Localization, Configuration or Resource

### ISSUE THREAD

**Issue by dee0** [open-component-model/ocm-project#68]
I would like to have objects 'feeding' each other like so 

ComponentVersion -> Localization -> Configuration -> FluxDeployer 

Where 
- Localization localizes values.yaml of a helm chart in my Component 
- Likewise for Configuration 
- FluxDeployer sets up the install of my helm chart

This doesn't work because Flux/Helm require that helm charts be in a namespaced repo instead of the being at the root of the registry.
The helm-controller complains about a 404 due to the path it is looking for not existing.

Currently this can be worked around by changing the above to be 
ComponentVersion -> Localization -> Configuration -> Resource -> FluxDeployer 
where Resource has 
extraIdentity:
    helmChart: my-helm-chart-name 

So the first question, why can't placement of extraIdentity on Configuration have the desired effect? 

Second problem is, even after introducing a Resource as described above the deploy fails because the only tag in the repo is 'latest'.    
  Helm complains that no tags were found in the repo.   

This is because Flux/helm require that the tags match a strict semver check and 'latest' doesn't pass this.    I don't understand why the tag is 'latest' when my ComponentVersion is festooned with version info.    Why can't one of those version numbers be utilized?

You can hack around this by adding a version spec on the resource like so 
    sourceRef:
      kind: Configuration
      name: *name
      resourceRef:
        name: chart
        version: "1.0.37"
Of course this isn't maintainable so this isn't a solution that one can live with.

And in any case, even adding the version still doesn't give you something that actually is usable.   This because the Resource is picking up the helm chart from the ComponentVersion instad of the Snapshot created from the Configuration.   Comparing resource_controller.go  and localization_controller.go ( see the findObjects func ) provides an idea of why Resource is not producing the desired results.

I can try and work around all of this by adding 
-  HelmRepository and HelmRelease to my component, and
- Changing Localization and Configuration to update HelmRepository and HelmRelease instead of my helm chart
Of course the HelmRelease would have a values section that would receive the config updates.

This is what the ocm demo [here](https://github.com/open-component-model/demo-secure-delivery) is doing.   However the problem with this approach is that I am now assuming that ops is using Flux for deploying my service.   I can accept the assumption that helm and ocm are in use but assuming Flux is too much.

Anyhoo as it stands at the processing of at least of the types Localization, Configuration or Resource needs to be changed in order to make it easier to consume helm charts as part of an ocm component.

I'll attach my component.yaml and the manifest file with the ComponentVersion etc.

**Comment by Skarlso** [comment]
I'll try testing helm access once I get to this issue. :) The first intended case should have worked 🤔 Not sure why `latest` was used I'll have to go through the code.

Thanks for reporting it.

**Comment by morri-son** [comment]
@Skarlso and @dee0 , the current way to do configuration and localization for me feels a bit to cumbersome. Thinking of people that want to deploy their Helm Chart, but understood that it makes sense to model their product in OCM should have a very simple possibility to configure and localize their application, similar to how they would by modifying the values.yaml, to specify their intent. If in the background we require CRs with a complex structure and content that establish the intent in the system, then we at least should check if it is possible to at least offer a more simple interface at the surface. Any ideas to solve this Gordian knot are welcome :-)

**Comment by Skarlso** [comment]
That is not going to be an easy task. :/ But I think it's gonna be fine maybe. It's just the re-packaging that's missing. A user would have a separate resource that contains configuration values perhaps, and we could merge that with existing ones, I don't know.

Another idea was to basically allow people to describe how to configure something by having the WASM scripts in a resource that would do the configuration for us. They are tiny binaries after all and we could just run them as is and it would configure the requested resource. 

That's also an option.

**Comment by morri-son** [comment]
WASM was and still is an interesting idea for the configuration and also still a hot topic [out there](https://www.linkedin.com/posts/philippeensarguet_kubecon-cloudnativecon-inference-activity-7178075254383116288-dOD4?utm_source=share&utm_medium=member_desktop). I would even buy something super simple for the bread and butter cases and something more complex for the other cases, but I really think that adoption will not raise when we keep the interface as complex as it is.

**Comment by Skarlso** [comment]
That might be true, yeah.

I have to do some brainstorming with myself and see if I can come up with something. Neverthless, a pluggable infrastructure is still the way to go I believe. It has been wildly successful in other areas after all.

**Comment by dee0** [comment]
Hey @Skarlso & @morri-son 

Want to restate the use case in our division and then present my naive thoughts on supporting them.

Use case : 
- There are teams that own the individual services that are to be deployed and there teams that own infrastructure.
- The service owning teams are expected to know helm
- The service owning teams should not need to know details about the infrastructure.   e.g.  If flux is used to install their helm chart they shouldn't need to know about it
- The service owning teams should know that OCM is used and should provide a schema etc that details how to localize and configure their service.   It is Ok if they also need to communicate to the infrastructure team 'extra identity' information and version information about the artifacts in their Component.   ( Note: We want to enable that the Component is the source of truth  ) 
- There is an infrastructure team that is aware of what services are to be installed and that provides infrastructure for providing last mile configuration to those services 
- Outside of the transported component case, the number of OCI repositories required should be minimized.   i.e.   If I have a Component repository already and I can have my helm chart as a local resource then I should not need yet another repository just for my helm chart.

From my naive user perspective, what is missing to support the above 'nicely' is: 
- I see [here](https://ocm.software/docs/cli/add/resources/) I can specify extra identity info and version information for my resources.    So I can, for example indicate that my dir localresource is a helmchart of version X.    And looking in my cluster I see the extra identity information and version information is already stored in the componentdescriptors.
  Unfortunately I can't actually set the helmChart extra identity when defining my component because of [this](https://github.com/open-component-model/ocm-project/issues/69) issue.   So even if the ocm controller would consume the info the ocm cli doesn't let me set it.    
- If the above were fixed _and_ then the mutationreconcilelooper could also be updated to
    - Use the extra identity information from within the componentdescriptor when constructing the repository name, and
    - Use the version info from within the componentdescriptors as the tag 

And with these mods I could have the simple 'pipeline' of 
ComponentVersion -> Localization ( helm chart ) -> Configuration ( helm chart ) -> FluxDeployer
as mentioned in the description of this ticket.

That said, even a change as simple as what is in this PR would make it so my use case is mostly supported.   The only catches would be 
- If ever helm starts insisting that the repo tag match the version inside Chart.yaml then things would break, and
- I need to introduce a Resource in order to get a repo name that helm is happy with ( e.g. ComponentVersion -> Localization -> Resource -> Configuration )    This isn't too bad because it is the infra team that would see this rather than the service teams.

Fwiw, I was hoping to step through the code to see how hard the naive solution above would be to implement.   This is why I left this PR in the 'work in progress' state.   Didn't find the time to do it today but maybe I'll get to it this week sometime.

**Comment by Skarlso** [comment]
Hello, let me try to clarify some things.

>Outside of the transported component case, the number of OCI repositories required should be minimized. i.e. If I have a Component repository already and I can have my helm chart as a local resource then I should not need yet another repository just for my helm chart.

I assume you are talking about our local registry? That is not something the service or the infrastructure team would be aware off at all. That registry is ocm-controller's local cache and an integration point with flux itself. The FluxDeployer creates Flux components to be able to deploy... with Flux. :) We are aiming to create other deployers like ArgoDeployer or something that can provide other kind of options, but that's in the future. For now, all you would need to be concerned about is defining the properties for a helm chart.


>Unfortunately I can't actually set the helmChart extra identity when defining my component because of https://github.com/open-component-model/ocm-project/issues/69 issue. So even if the ocm controller would consume the info the ocm cli doesn't let me set it.

The extra-identity is used by us. OCM the library isn't aware of such a thing. So specifying it there, does nothing. That's why you are getting that error.

>ComponentVersion -> Localization ( helm chart ) -> Configuration ( helm chart ) -> FluxDeployer
as mentioned in the description of this ticket.

The reason it doesn't work today is because this feature is incomplete as of now. Like I detailed in my comment, the Resource can produce a valid helm chart, but the others can't yet. :) Once it's implemented your scenario should work nicely. 🤞 😄 

>If ever helm starts insisting that the repo tag match the version inside Chart.yaml then things would break, and

The version is coming from here:

```yaml
components:
- name: github.com/open-component-model/helm-test
  version: "v1.0.0"
  provider:
    name: ocm.software
  resources:
  - name: charts
    type: helmChart
    version: 6.3.5
    input:
      type: helm
      version: 6.3.5
      path: charts/podinfo-6.3.5.tgz
```

So technically you can define whatever version you like when building the helm component using OCM the library.

Then, the resource uses that version as well when it's being reconciled:

```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-with-helm-deployment
  namespace: ocm-system
spec:
  interval: 10m
  sourceRef:
    kind: ComponentVersion
    name: ocm-with-helm
    namespace: ocm-system
    resourceRef:
      name: charts
      version: 6.3.5
      extraIdentity:
        helmChart: podinfo
```

>ComponentVersion -> Localization -> Resource -> Configuration

Hopefully, once everything is implemented, the Resource part could simply be left off. 🤞

**Comment by dee0** [comment]
Hey @Skarlso 

First, let me say 'thank you' for taking the time to respond and having the patience deal with me. :)   

_"I assume you are talking about our local registry? "_

Nope.   I explained this above.   Please see the screenshot above of artifactory.    I circled the extra repository that was created and I explained why this is a problem.

_"The extra-identity is used by us. OCM the library isn't aware of such a thing. So specifying it there, does nothing. That's why you are getting that error."_  

You must be able to see this makes zero sense from my perspective, yes?   Consider what I am seeing as an outsider looking in 
- CLI documentation says I can set extra identity info but doesn't explain what it is for
- Resource documentation, as seen from kubectl explain, says I can set extra identity info including 'helmchart'.  Also doesn't explain what it is for.
- Setting helmChart extra identity info on Resource gives me some behaviour I need
- But setting helmChart, camel-case, via the CLI gives me an error
- As a user I am not appreciative of the difference between OCM and the OCM controller. ( Well I am a bit because I have played with the stuff for too long.    However the people I am trying to convince to adopt OCM have no idea about the distinction )
- From what I have seen so far, the extra identity info that I provide to the CLI just gets chucked into the componentdescriptor object in kubernetes but doesn't get used.    That is, for the stuff the cli does accept  is just metadata along for the ride.   So why complain that I use 'helmChart' vs 'helmchart'?    Or why not ConstructRepositoryName recognize 'helmchart' as well as 'helmChart'? 

Regarding this example
```
components:
- name: github.com/open-component-model/helm-test
  version: "v1.0.0"
  provider:
    name: ocm.software
  resources:
  - name: charts
    type: helmChart
    version: 6.3.5
    input:
      type: helm
      version: 6.3.5
      path: charts/podinfo-6.3.5.tgz
```
it is problematic for these reasons I mentioned above : 
- If I use the helmChart type then helm chart is stored in a separate repository, it isn't a local resource ( Again see screenshot above etc ) 
- If I pull in the chart as a tgz, instead of a directory, then I can't localize or configure the values.yaml in the chart

So again, from perspective, this should be an easy fix that doesn't break the model
- Either let ConstructRepositoryName recognize 'helmchart' as well as 'helmChart' or let the cli accept upper case letters
- Have mutation_reconciler_looper use the extra identity and version info I provide in my component description

Then in my component descriptor yaml I can put
```
name: dmi.csi.sap/dmi-multicloud-service-provisioner2
version: &version "1.0.74" # Doesn't seem to affect tags
provider:
  name: dmi.csi.sap
resources:
- name: chart 
  type: dir 
  version: "1.0.75" 
  extraIdentity:
    helmchart: "mychart"
  input: 
    type: dir 
    path: ../helm/dmi-multicloud-service-provisioner
    compress: true 
    preserveDir: true

```
and everything will 'just work' :) 

Btw, the above is giving me the following  in my componentdescripto, note the extraIdentity and version.     So the information needed to do the right thing is there, just Localize and Configuration need to use it
```
 componentReferences: []
  name: dmi.csi.sap/dmi-multicloud-service-provisioner2
  provider: dmi.csi.sap
  repositoryContexts: []
  resources:
    - access:
        localReference: sha256:645d3bf820707f82872a2766c423ea4303e4e4b462fa986429470e90420d247c
        mediaType: application/x-tgz
        type: localBlob
      digest:
        hashAlgorithm: SHA-256
        normalisationAlgorithm: genericBlobDigest/v1
        value: 645d3bf820707f82872a2766c423ea4303e4e4b462fa986429470e90420d247c
      extraIdentity:
        helmchart: mychart
      name: chart
      relation: local
      type: dir
      version: 1.0.75

```

**Comment by Skarlso** [comment]
Okay, so I think we have to make something clear. The controller is using OCM LIBRARY. Whatever the CLI does is the CLI's thing. :) The controller is using the Library.

So whatever the CLI does is not necessarily something the controller does. The controller has different goals and purposes.

This means that your component description doesn't need the extra identity the controller needs. Here: https://github.com/open-component-model/ocm-controller?tab=readme-ov-file#helmchart-type-resource it's explained that the controller is using this because it cannot be inferred. This is the only reason for it.

I could extend this of course if it doesn't make any sense. :)

Sorry, I might be dense, but where / what is creating that extra repo? 

>The chart is in a separate repo, which is something we don't want

But why?

So like I wrote, for now, configuration and localization isn't working with charts yet. I need to add that functionality. Resource though works with charts as long as OCM can fetch them. Whatever it creates internally, is not a concern of the user.

**Comment by dee0** [comment]
_"what is creating that extra repo?"_

The extra repository is created by the command
`ocm --cred :type=OCIRegistry --cred :hostname=XXX --cred username=YYY --cred 'password=ZZZ' transfer component  ./component-archive XXX/csi-ocm-poc`

_**The chart is in a separate repo, which is something we don't want** But why?_

Because at least here, there is administrative overhead in having an additional repository that is used for production resources
- Need to negation with teams running the registries servers so that you can have it and so that has the capacity you need (  5 tags, 10 tags, .... ) 
- Need to maintain the access control to it 
- Need to document it and maintain documentation for it
- Need to re-explain to administrators and security people who forget why you need or who never read the doc why you need it

**Comment by Skarlso** [comment]
Ahhhhh. I see. So ocm cli is creating it. I... can't do anything about that I'm afraid. :D

**Comment by morri-son** [comment]
> In the attached image I have circled in red the extra repo. The problem with the extra repo is that then we have to negotiate with the teams managing the various repositories we have to work with to request permission for 2 repositories instead of 1. Basically it will double the 'paperwork' involved in getting this to work.

Hi @dee0 , the first repository "component-descriptors" is created the first time a transfer of a component version to <my registry>/<my repo> happens. It only stores the component versions, nothing else. If your component version only contains references to external resources, it will be the only repository created in the OCI registry. Did you transfer the component using the -V / --copy-resources option? This is trying to copy the resources to the same repository name as in the source if available. 

```
component:
  name: ocm.software/demos/echoserver
  provider:
    name: ocm.software
  resources:
  - access:
      imageReference: ealen/echo-server:0.9.2
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 0.9.2
  version: 0.9.2
```

**Comment by dee0** [comment]
Hey @morri-son 

Thanks for chiming in.

No, I didn't use either of -V or --copy-resources.   The command line I have been using is :

`ocm --cred :type=OCIRegistry --cred :hostname=XXX --cred username=YYY --cred 'password=ZZZ' transfer component  ./component-archive XXX/csi-ocm-poc`

**Comment by Skarlso** [comment]
I believe this is now fixed with the recent move to OCI repos and a bit of a better handling of helm charts with removing the need to the name and tagging and everything.

@dee0 If you have the time, please re-test this. In the meantime, I'm gonna close it as fixed. Please re-open it if the problem persists. :)

**Comment by dee0** [comment]
Hey @Skarlso 

Should I building and testing the main branch or should I test with the latest release?

**Comment by Skarlso** [comment]
Latest release should be okay now.

**Comment by dee0** [comment]
Hey @Skarlso 

My first attempt to use the latest ocm-controller failed.  I am still investigating however what I can tell you  is :
- We have 'landscapes' which are collections of k8s clusters of different types.   Types -> different cluster config, different services deployed.   
- I have on boarded 4  services to OCM, two that only go to one cluster type and two that only go to another.
- For one cluster type tests failed because a key service for the type didn't get deployed.   However for the other cluster type there was no problem reported
- For the one where the was a problem, all FluxDeployers didn't enter ready state cause HelmRelease v2 isn't present.  I checked the cluster and I see that HelmRelease v2beta1 and v2beta2 are present but not v2
- For the one where no problem was reported, I have not yet checked if there was really no problem or if there just is no test that would detect a problem

Will provide updates as I get more data

**Comment by Skarlso** [comment]
HelmRelease ->

**Comment by dee0** [comment]
@Skarlso 

Ok, for the cluster that hadn't reported a problem it turned out to fail the same way as the one did.    There was quite some latency between the test completion and the results being collected.

So, first problem with updating to the ocm controller v0.23.7 is that it requires an update to the flux controllers.    To deploy, I am using the output from ocm dry run after running it through a script that 'templatizes' it.     Hopefully if I was using the cli to directly deploy or if I was using the new helm chart I would have received a warning about this.

Yesterday morning I upgraded all of the flux controllers to the latest release and kicked off another test.   Looking at the results this morning I see that the upgrade has broken my POC.    I haven't reviewed all the data yet, but the thing I see immediately is that the FluxDeployers aren't healthy.   They have status like 
```
  status:
    conditions:
      - lastTransitionTime: "2024-06-24T17:48:35Z"
        message: 'failed to create Helm Release object :failed to create reconcile kustomization: HelmRelease.helm.toolkit.fluxcd.io "dmi-broker" is invalid: [spec.chart.spec.sourceRef.name: Invalid value: "": spec.chart.spec.sourceRef.name in body should be at least 1 chars long, spec: Invalid value: "object": either chart or chartRef must be set]'
        observedGeneration: 2
        reason: CreateOrUpdateHelmFailed
        status: "True"
        type: Stalled
      - lastTransitionTime: "2024-06-24T17:48:35Z"
        message: 'failed to create Helm Release object :failed to create reconcile kustomization: HelmRelease.helm.toolkit.fluxcd.io "dmi-broker" is invalid: [spec.chart.spec.sourceRef.name: Invalid value: "": spec.chart.spec.sourceRef.name in body should be at least 1 chars long, spec: Invalid value: "object": either chart or chartRef must be set]'
        observedGeneration: 2
        reason: CreateOrUpdateHelmFailed
        status: "False"
        type: Ready
    observedGeneration: 2
```

No idea why it is mentioning kustomizations.    I am not using those at all.

**Comment by Skarlso** [comment]
That's a typo. It should be HelmRelease. What's your setup look like now? The new version updated the spec and the way we use HelmCharts to align with the new Flux version.

Here is a project that uses helm charts properly: https://github.com/Skarlso/ocm-helm

Component Version
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-with-helm
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/open-component-model/helm-test
  version:
    semver: 1.0.3
  repository:
    url: ghcr.io/skarlso/helm-test
    secretRef:
      name: creds
```

Resource:
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-with-helm-deployment
  namespace: ocm-system
spec:
  interval: 10m
  sourceRef:
    kind: ComponentVersion
    name: ocm-with-helm
    namespace: ocm-system
    resourceRef:
      name: charts
      version: 6.3.5
```

Deployer:
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: fluxdeployer-podinfo-pipeline-backend
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: Resource
    name: ocm-with-helm-deployment
  helmReleaseTemplate:
    interval: 5m
```

**Comment by dee0** [comment]
To recap my setup, I have this setup
![image](https://github.com/open-component-model/ocm-project/assets/8633549/f3621ea1-07ce-49aa-9543-936414219edc)

Here is my FluxDeployer

```
- apiVersion: delivery.ocm.software/v1alpha1
  kind: FluxDeployer 
  metadata:
    name: *name 
    namespace: *ocm-sys-namespace
  spec:
    interval: 10s 
    sourceRef:
      kind: Configuration
      name: *name
      namespace: *namespace
    helmReleaseTemplate:
      timeout: 1h
      chart:
        spec:
          chart: *name
      interval: 10s
      targetNamespace: *namespace
      valuesFrom:
      - kind: Secret 
        name: *landscapeSecretName
        valuesKey: *secretKey
```

The Configuration status indicates they are healthy.

**Comment by dee0** [comment]
For completeness sake, the FluxDeployer above was from a helm template.   Here is the rendered result

```
- apiVersion: delivery.ocm.software/v1alpha1
  kind: FluxDeployer
  metadata:
    creationTimestamp: "2024-06-24T17:46:20Z"
    generation: 2
    labels:
      hc.sap.com/hc-provisioned: "True"
    name: dmi-broker
    namespace: ocm-system
    resourceVersion: "19542"
    uid: 5343f112-0df2-4c70-96d2-3dc3d8e7d41e
  spec:
    helmReleaseTemplate:
      chart:
        spec:
          chart: dmi-broker
      interval: 10s
      targetNamespace: broker
      timeout: 1h
      valuesFrom:
        - kind: Secret
          name: dmi-broker-from-landscape
          valuesKey: secret
    interval: 10s
    sourceRef:
      apiVersion: delivery.ocm.software/v1alpha1
      kind: Configuration
      name: dmi-broker
      namespace: broker
```

**Comment by dee0** [comment]
Hey @Skarlso 
At the moment I think what I am seeing is a new ocm-controller bug.   It isn't filling in the helmReleaseTemplate sourceRef properly.

**Comment by Skarlso** [comment]
Gonna need some more info about your CRs. Or logs or something. Otherwise you're on your own.

**Comment by dee0** [comment]
Logs don't show really show anything more than what is in that status message.
Attaching a zip of the ocm CRs
[ocm-crs-2024-06-25.zip](https://github.com/user-attachments/files/15974743/ocm-crs-2024-06-25.zip)

Each resource type is in its own *.yml file.   Fwiw this is what our testing infrastructure is spitting out at the end of a failed test run.

Fwiw, this was working until the upgrade.

**Comment by Skarlso** [comment]
This:
```yaml
      resourceRef:
        extraIdentity:
          helmChart: dmi-broker

```

This is also no longer correct for the flux deployer:

```yaml
    helmReleaseTemplate:
      chart:
        spec:
          chart: dmi-broker
```

Will no longer work. Please check out the repository I linked. There is a working example for both helm chart without and wit
h configuration. :)

**Comment by dee0** [comment]
Hey @Skarlso 

Thanks, but I think your sample may be broken and I don't think it is representative for my case.   

I think it is broken because the [Localization](https://github.com/Skarlso/ocm-helm/blob/688c5707e4ebea3de83cdf11a0846ffbc734920a/components/localization.yaml) appears to refer to a non-existent Resource.   It refers to `resource-pipeline-backend` and when I search for that the only hit is in localization.yaml.    

As for why I don't think the samples are representative of my case there are these discrepancies 
- I am using both Localization and Configuration ( presumably this is normal ) but the examples don't use them in combination
- My chart is a local resource.   At the time when I was putting things together it didn't seem that I could localize or configure the chart's values.yaml so long as it was in a tgz file.    So if that isn't the case using a tgz would be fine
    
 ```
        resources:
        - name: chart 
          version: *version
          type: dir
          input: 
            type: dir
            path: "../helm/dmi-broker"
            preserveDir: true
            compress: true 
```

- In your examples the delivery.ocm.software resources are referring to specific chart versions.   I can't do that.   Whatever version happens to be  in the ComponentVersion is what should be used.
    
Please provide some guidance on how to make this work with whatever change you made to the ocm-controller.

**Comment by Skarlso** [comment]
Ahhh sorry. I should have said that only configuration was altered to be working. The localization wasn't touched.

So sorry Dan.

**Comment by Skarlso** [comment]
I'll try to whip up a localization for you that's working. But generally I think it should once you alter it the same way configuration does it. Only the location of the image and tag needs to follow the value.yaml's format.

**Comment by dee0** [comment]
Thanks @Skarlso 

Btw, the things I am concerned about are 
- That Configuration can operate on the output of Localization 
- That there is no requirement to hard code a chart version in any of the delivery objects ( Localization, Configuration, FluxDeployer )

**Comment by Skarlso** [comment]
Hum. That shouldn't matter I think. Dir should work.

The requirement is there because it will try and produce a snapshot that the helm controller than needs to understand. And we do that previously already but that information isn't taken any further. Unless the resource is the same version as the chart than that extra info is not needed.

**Comment by dee0** [comment]
Hey @Skarlso just want to confirm what I think you said...   In my component description if the resource version matches the helm chart version then I don't have to specify a version in the Resource or the FluxDeployer.    So for example, in my component yaml if I have 

```
name: dmi.csi.sap/dmi-broker
version: &version "1.0.0-1.badcafe"
provider:
  name: dmi.csi.sap
resources:
- name: chart 
  version: 1.2.3  # <!-- Matches the helm chart version 
  type: dir
  input: 
    type: dir
    path: "../helm/dmi-broker"
    preserveDir: true
    compress: true 

```

then I won't need to specify a chart version in the Resource or the FluxDeployer.    

Do I have that correct?

**Comment by Skarlso** [comment]
Yeah, that should be right. As long as the tag in the snapshot matches the chart, Flux's helm controller shouldn't complain. 🤞

**Comment by dee0** [comment]
Nope, something went wrong.
I'll dig some more, but what I am seeing is 

```
kubectl --kubeconfig=kubeconfig-644-e1-dmi get -A helmrelease
NAMESPACE    NAME         AGE   READY   STATUS
ocm-system   dmi-broker   29m   False   artifact revision 19090 does not match chart version 1.3.0-1085.xeae3fba.14
```

I have no idea where 19090 is coming from.   Looking at the component descriptor with 
```
kubectl --kubeconfig=kubeconfig-644-e1-dmi get -n broker componentdescriptor dmi.csi.sap-dmi-broker-1.3.0-1085.xeae3fba.14-17027996690744119944 -o=yaml
```

I see 
```
spec:
  resources:
  - access:
      localReference: sha256:4b942c25c3e772c826959cb4702a3e3d9f9b59be4a78449a15f7e5be4d5e4e12
      mediaType: application/x-tgz
      type: localBlob
    digest:
      hashAlgorithm: SHA-256
      normalisationAlgorithm: genericBlobDigest/v1
      value: 4b942c25c3e772c826959cb4702a3e3d9f9b59be4a78449a15f7e5be4d5e4e12
    name: chart
    relation: local
    type: dir
    version: 1.3.0-1085.xeae3fba.14
```
