### ISSUE TITLE
Create Helm Charts for the controllers

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-project#83]
Create a new repository called ocm-helm-charts.

This repository should publish helm charts for the controllers.

The chart should have options to turn off and on certain elements of it but by default it would install all the relevant controllers for MPAS.

The repository for the chart can be `ghcr.io/open-component-model/helm/ocm-controllers` for example and can be published really easily with a github action such as:

```yaml
- name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Build and release the helm charts
        run: |
          helm registry login ghcr.io -u open-component-model -p ${{ secrets.GITHUB_TOKEN }}
          helm package --version ${{ steps.prep.outputs.VERSION }} --app-version ${{ steps.prep.outputs.VERSION }} ./helm
          helm push ${{ github.event.repository.name }}-${{ steps.prep.outputs.VERSION }}.tgz oci://ghcr.io/open-component-model/helm
```

Once this is done, I believe we can increase the visibility of the charts using https://artifacthub.io/ and publishing there.

The artifact.yaml file should look something like this:

```yaml
repositoryID: # <get this after registering at artifacthub.io>
owners:
  - name: open-component-model
    email: ocm@ocm.software
```

Add a README to the repository that explains how to use it, and add instructions and values.

We could also provide an option to just install CRDs.

Switch to using Helm charts and CRDs only. We can use `helm template` to generate the install manifest.
Also, generate all CRDs into deploy/crds instead of base.

Will have the added benefit that people will be able to configure certificates during installation.

This will also get rid of the need to set the version in the kustomize file. It will actually provide a pretty neat way of customizing a whole lot of things for the user.
